import { joinSession } from "@github/copilot-sdk/extension";
import { readFileSync, writeFileSync, appendFileSync, mkdirSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";

// ─── Insight Categories ──────────────────────────────────────────────
const CATEGORIES = {
  decision:     { emoji: "⚖️",  label: "Decision" },
  pattern:      { emoji: "🔧", label: "Pattern" },
  debug:        { emoji: "🐛", label: "Debug" },
  security:     { emoji: "🔒", label: "Security" },
  regulatory:   { emoji: "⚠️",  label: "Regulatory" },
  comparison:   { emoji: "📊", label: "Comparison" },
  architecture: { emoji: "🏗️",  label: "Architecture" },
  performance:  { emoji: "⚡", label: "Performance" },
  learning:     { emoji: "📚", label: "Learning" },
};

// ─── Find Insights Directory ─────────────────────────────────────────
function findInsightsDir() {
  let dir = process.cwd();
  for (let i = 0; i < 10; i++) {
    const candidate = join(dir, "NexSynapse", "docs", "insights");
    if (existsSync(join(dir, "NexSynapse"))) {
      if (!existsSync(candidate)) {
        mkdirSync(candidate, { recursive: true });
      }
      return candidate;
    }
    const parent = resolve(dir, "..");
    if (parent === dir) break;
    dir = parent;
  }
  const fallback = join(process.cwd(), "NexSynapse", "docs", "insights");
  mkdirSync(fallback, { recursive: true });
  return fallback;
}

// ─── Log File Header ─────────────────────────────────────────────────
const LOG_HEADER = `# NexSynapse Insight Log

> Auto-captured insights, decisions, and learnings.
> Generated by the insight-capture extension.
> Each entry is timestamped and tagged for searchability.

---
`;

// ─── Document Insight Tool ───────────────────────────────────────────
async function documentInsight({ category, title, content, tags }) {
  const dir = findInsightsDir();
  const logFile = join(dir, "insight-log.md");
  const cat = CATEGORIES[category] || { emoji: "💡", label: "General" };
  const timestamp = new Date().toISOString();
  const dateStr = timestamp.split("T")[0];
  const timeStr = timestamp.split("T")[1].split(".")[0];
  const tagsStr = tags && tags.length > 0
    ? tags.map(t => `\`${t}\``).join(", ")
    : "";

  const entry =
    `\n### ${cat.emoji} ${title}\n\n` +
    `| Field | Value |\n` +
    `|-------|-------|\n` +
    `| Category | ${cat.label} |\n` +
    `| Date | ${dateStr} ${timeStr} UTC |\n` +
    (tagsStr ? `| Tags | ${tagsStr} |\n` : "") +
    `\n${content}\n\n---\n`;

  if (!existsSync(logFile)) {
    writeFileSync(logFile, LOG_HEADER, "utf-8");
  }

  appendFileSync(logFile, entry, "utf-8");

  const full = readFileSync(logFile, "utf-8");
  const count = (full.match(/^### /gm) || []).length;

  return (
    `✅ Insight documented: "${title}"\n` +
    `📁 File: ${logFile}\n` +
    `🏷️ Category: ${cat.emoji} ${cat.label}\n` +
    (tagsStr ? `🔖 Tags: ${tagsStr}\n` : "") +
    `📊 Total insights: ${count}`
  );
}

// ─── List Insights Tool ──────────────────────────────────────────────
async function listInsights() {
  const dir = findInsightsDir();
  const logFile = join(dir, "insight-log.md");

  if (!existsSync(logFile)) {
    return "📋 No insights captured yet. Use `document_insight` to save one.";
  }

  const content = readFileSync(logFile, "utf-8");
  const entries = content.match(/^### .+$/gm) || [];

  if (entries.length === 0) {
    return "📋 Insight log exists but is empty.";
  }

  const listing = entries
    .map((e, i) => `${i + 1}. ${e.replace("### ", "")}`)
    .join("\n");

  return (
    `📋 **${entries.length} insight(s) captured**\n\n` +
    listing +
    `\n\n📁 Full log: ${logFile}`
  );
}

// ─── Search Insights Tool ────────────────────────────────────────────
async function searchInsights({ query }) {
  const dir = findInsightsDir();
  const logFile = join(dir, "insight-log.md");

  if (!existsSync(logFile)) {
    return "📋 No insights captured yet.";
  }

  const content = readFileSync(logFile, "utf-8");
  const sections = content.split(/(?=^### )/gm).filter(s => s.startsWith("### "));

  const terms = query.toLowerCase().split(/\s+/);
  const matches = sections.filter(section => {
    const lower = section.toLowerCase();
    return terms.some(term => lower.includes(term));
  });

  if (matches.length === 0) {
    return `🔍 No insights matching "${query}" found (${sections.length} total entries).`;
  }

  const titles = matches.map(m => {
    const firstLine = m.split("\n")[0];
    return firstLine.replace("### ", "");
  });

  return (
    `🔍 **${matches.length} insight(s) matching "${query}":**\n\n` +
    titles.map((t, i) => `${i + 1}. ${t}`).join("\n") +
    `\n\n---\n\nFull entries:\n\n` +
    matches.join("\n")
  );
}

// ─── Auto-Trigger Patterns ──────────────────────────────────────────
const INSIGHT_TRIGGERS = [
  /\b(document this|save this|capture this|record this|log this)\b/i,
  /\b(remember this|note this|write this down)\b/i,
  /\b(documentar esto|guardar esto|recordar esto|anotar esto)\b/i,
  /\b(insight|key finding|takeaway|lesson learned|important)\b/i,
  /\b(decided to|chose .+ over|trade-?off|went with)\b/i,
  /\b(root cause|bug was|fixed by|the issue was)\b/i,
  /\b(discovered|realized|found that|turns out)\b/i,
  /\b(best practice|anti-pattern|code smell|pattern)\b/i,
  /\b(benchmark|comparison|efficiency|performance result)\b/i,
  /\b(security finding|vulnerability|owasp|compliance)\b/i,
  /\b(aprendimos|decidimos|descubrimos|hallazgo|lección)\b/i,
  /\b(causa raíz|el error era|se resolvió)\b/i,
];

// ─── Session Join ────────────────────────────────────────────────────
const session = await joinSession({
  hooks: {
    onUserPromptSubmitted: async ({ input }) => {
      const prompt = input.prompt || "";
      const matched = INSIGHT_TRIGGERS.some(re => re.test(prompt));

      if (matched) {
        return {
          instructions:
            `💡 **Insight-worthy content detected.** The user's message suggests a decision, ` +
            `finding, comparison, or learning worth preserving. If a meaningful insight emerged ` +
            `from this conversation, use the \`document_insight\` tool to save it.\n\n` +
            `Categories: decision, pattern, debug, security, regulatory, comparison, ` +
            `architecture, performance, learning.\n` +
            `Include descriptive tags for future searchability.`,
        };
      }
      return {};
    },
  },
  tools: [
    {
      name: "document_insight",
      description:
        "Save a project insight, decision, or learning to the structured insight log. " +
        "Use when a meaningful finding, architectural decision, debugging root cause, " +
        "cost comparison, or best practice emerges during conversation. " +
        "Insights are persisted to NexSynapse/docs/insights/insight-log.md for cross-session recall.",
      parameters: {
        type: "object",
        properties: {
          category: {
            type: "string",
            description:
              "Insight category: decision (trade-offs, choices), pattern (reusable code), " +
              "debug (root cause/fix), security (OWASP/vulnerability), regulatory (compliance), " +
              "comparison (benchmarks/efficiency), architecture (system design), " +
              "performance (optimization), learning (general takeaway)",
            enum: Object.keys(CATEGORIES),
          },
          title: {
            type: "string",
            description:
              "Short descriptive title (e.g., 'NexSynapse saves $4,300-7,700/yr vs alternatives')",
          },
          content: {
            type: "string",
            description:
              "The insight content — what was learned, decided, or discovered. " +
              "Include context, rationale, data, and any relevant numbers.",
          },
          tags: {
            type: "array",
            items: { type: "string" },
            description:
              "Searchable tags for future recall (e.g., ['pricing', 'opus', 'benchmark'])",
          },
        },
        required: ["category", "title", "content"],
        additionalProperties: false,
      },
      handler: async (args) => documentInsight(args),
    },
    {
      name: "list_insights",
      description:
        "List all captured insights from the insight log with titles and categories.",
      parameters: {
        type: "object",
        properties: {},
        additionalProperties: false,
      },
      handler: async () => listInsights(),
    },
    {
      name: "search_insights",
      description:
        "Search the insight log for entries matching a keyword or phrase. " +
        "Returns matching insight titles and full content.",
      parameters: {
        type: "object",
        properties: {
          query: {
            type: "string",
            description: "Search term or phrase to find in the insight log",
          },
        },
        required: ["query"],
        additionalProperties: false,
      },
      handler: async (args) => searchInsights(args),
    },
  ],
});
