using EscrowApp.Models;
using FluentAssertions;
using Microsoft.AspNetCore.Identity;
using Xunit;

namespace EscrowApp.Tests.Models;

/// <summary>
/// Unit tests for ApplicationUser (ASP.NET Core Identity integration).
/// Tests that ApplicationUser properly extends IdentityUser and maintains Actor linkage.
/// </summary>
public sealed class ApplicationUserTests
{
    [Fact]
    public void Create_ValidUser_SetsEmailAndUsername()
    {
        // Arrange
        const string email = "test@example.com";

        // Act
        var user = new ApplicationUser
        {
            UserName = email,
            Email = email
        };

        // Assert
        user.UserName.Should().Be(email);
        user.Email.Should().Be(email);
    }

    [Fact]
    public void Create_WithActorId_StoresActorForeignKey()
    {
        // Arrange
        const int actorId = 42;
        const string email = "consultant@example.com";

        // Act
        var user = new ApplicationUser
        {
            UserName = email,
            Email = email,
            ActorId = actorId
        };

        // Assert
        user.ActorId.Should().Be(actorId);
    }

    [Fact]
    public void Create_WithoutActorId_AllowsNullForFutureWeb3Linkage()
    {
        // Arrange
        const string email = "user@example.com";

        // Act
        var user = new ApplicationUser
        {
            UserName = email,
            Email = email
            // ActorId omitted — should be null
        };

        // Assert
        user.ActorId.Should().BeNull();
    }

    [Fact]
    public void Create_ExtendsIdentityUser_HasInheritedProperties()
    {
        // Arrange & Act
        var user = new ApplicationUser { Email = "test@example.com" };

        // Assert: Verify IdentityUser<int> inheritance
        user.Should().BeAssignableTo<IdentityUser<int>>();
        
        // Verify key inherited properties exist
        user.Id.Should().Be(0); // Not set yet
        user.SecurityStamp.Should().BeNull();
        user.ConcurrencyStamp.Should().NotBeNull(); // Auto-generated by Identity on instantiation
        user.LockoutEnabled.Should().BeFalse(); // Default
    }

    [Fact]
    public void Serialization_UserCanBeSerializedForStorage()
    {
        // Arrange
        var user = new ApplicationUser
        {
            Id = 1,
            UserName = "test@example.com",
            Email = "test@example.com",
            ActorId = 5,
            SecurityStamp = "stamp123"
        };

        // Act: Verify properties are accessible
        var email = user.Email;
        var actorId = user.ActorId;

        // Assert
        email.Should().Be("test@example.com");
        actorId.Should().Be(5);
    }
}
